#include <stdio.h>
int main(void)
{
    int exchange_rate,exchange_mate, dollar, won, way, way2, way3;
    int result_value;
    int result_value2;
    char day[30];
    char time[30];
    char play[30];
    char result_str[20];

    {
        printf("========================================================================\n");
        printf("원하시는 서비스를 선택해주세요\n");
        printf("1. 여행계획\n");
        printf("2. 환율계산기\n");
        printf("3. 준비물\n");
        printf("4. 프로그램 종료\n");
        printf("========================================================================\n");
        scanf_s("%d", &way);

        printf("%d번 서비스를 선택하셨습니다.\n", way);

        if (way == 1)
        {
            while (1)
            {
                printf("========================================================================\n");
                printf("원하시는 서비스를 선택해주세요\n");
                printf("1. 여행계획 입력하기\n");
                printf("2. 여행계획 조회하기\n");
                printf("3. 여행계획 수정하기\n");
                printf("4. 이전으로 돌아가기\n");
                printf("========================================================================\n");
                scanf_s("%d", &way2);

                printf("%d번 서비스를 선택하셨습니다.\n", way2);

                if (way2 == 1)
                {
                    printf("========================================================================\n");
                    printf("몇 일차 인가요?\n");
                    scanf_s("%s", day,10);
                    printf("시간이 어떻게 되나요?\n");
                    scanf_s("%s", time, 10);
                    printf("어떤 일을 하나요?\n");
                    scanf_s("%s", play, 10);
                    break;
                }
                else if (way2 == 2)
                {
                    printf("========================================================================\n");
                    break;
                }
                else if (way2 == 3)
                {

                }
                else if (way2 == 4)
                {
                    break;
                }
                else
                {
                    printf("다시 입력해주세요.");
                    continue;
                }
            }
        }
        else if (way == 2)
        {
            printf("========================================================================\n");
            printf("현재 달러에 대한 원화 환율을 입력해주세요(소수점 불가능) >> ");
            scanf_s("%d", &exchange_rate);

            printf("========================================================================\n");
            printf("현재 엔에 대한 원화 환율을 입력해주세요(소수점 불가능) >> ");
            scanf_s("%d", &exchange_mate);

            while (2)
            {
                printf("========================================================================\n");
                printf("========환율 계산기========\n");
                printf("1.원->달러\n");
                printf("2.원->엔\n");
                printf("3.달러->원\n");
                printf("4.엔-> 원\n");
                printf("5.이전으로 돌아가기\n");
                printf("========================================================================\n");
                scanf_s("%d", &way3);

                printf("%d번 서비스를 선택하셨습니다.\n", way3);
                
                if (way3 == 1)
                {
                    printf("========================================================================\n");
                    printf("바꿀 원화를 입력해주세요 >> ");
                    scanf_s("%d", &won);
                    result_value = won / exchange_rate;
                  
                    printf("결과값 : %d달러 입니다.\n", result_value);
                    break;
                }
                else if (way3 == 2)
                {
                    printf("========================================================================\n");
                    printf("바꿀 달러를 입력해주세요 >> ");
                    scanf_s("%d", &dollar);

                    result_value2 = dollar * exchange_rate;
                    printf("결과값 : %d원 입니다.\n", result_value2);
                    break;
                }
                eelse if (way3 == 3)
                {
                    printf("========================================================================\n");
                    printf("바꿀 원화을 입력해주세요");
                    scanf_s("%d", &won);
                    result_value3 = won / exchange_mate;

                    printf("결과값 : %d엔 입니다.\n", result_value3);
                    break;
                }
                else if (way3 == 4)
                {
                    printf("========================================================================\n");
                    printf("바꿀 엔화을 입력해주세요");
                    scanf_s("%d", &won);
                    result_value4 = exchange_mate * won;

                    printf("결과값 : %d엔 입니다.\n", result_value4);
                    break;
                }
                else
                {
                    printf("다시 입력해주세요.");
                    continue;
                }

            }

        }

    }

}
